/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_nativelib_NativeMath */

#ifndef _Included_com_example_nativelib_NativeMath
#define _Included_com_example_nativelib_NativeMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_nativelib_NativeMath
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_nativelib_NativeMath_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif

// Made with Bob
